version: '3'
services:
  db:
    container_name: hair_salon_db
    image: postgres:16
    restart: always
    volumes:
      - ./hair_salon_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '3334:5432'

